// Generated by scripts/bake-thumbs.mjs (`pnpm bake:thumbs`) — do not edit by hand.
// Re-run the bake when the default view, the style list, or upstream tiles change;
// until then this file and its images are checked in so a deploy never regenerates them.
import type { BakedThumb } from '../../bakedThumbs';

import t0 from './b-carto-dark.webp';
import t1 from './b-liberty.webp';
import t2 from './b-none-dark.webp';
import t3 from './b-none-light.webp';
import t4 from './b-ofm-bright.webp';
import t5 from './b-ofm-dark.webp';
import t6 from './b-ofm-positron.webp';
import t7 from './b-satellite.webp';
import t8 from './s-heatmap-dark.webp';
import t9 from './s-heatmap-light.webp';
import t10 from './s-heightmap-dark.webp';
import t11 from './s-heightmap-light.webp';
import t12 from './s-hillshade.webp';
import t13 from './s-none-dark.webp';
import t14 from './s-none-light.webp';

export const BAKED_THUMBS: BakedThumb[] = [
  { spec: {"basemap":"carto-dark","basemapVisible":true,"shading":"hillshade","shadingVisible":true,"exposure":null,"terrainScale":1}, camera: [7.718276497838673,46.017693318286575,12.873741518690931,78.00000000000001,-135], url: t0 },
  { spec: {"basemap":"liberty","basemapVisible":true,"shading":"hillshade","shadingVisible":true,"exposure":null,"terrainScale":1}, camera: [7.718276497838673,46.017693318286575,12.873741518690931,78.00000000000001,-135], url: t1 },
  { spec: {"basemap":"carto-dark","basemapVisible":false,"shading":"hillshade","shadingVisible":true,"exposure":null,"terrainScale":1}, camera: [7.718276497838673,46.017693318286575,12.873741518690931,78.00000000000001,-135], url: t2 },
  { spec: {"basemap":"carto-light","basemapVisible":false,"shading":"hillshade","shadingVisible":true,"exposure":null,"terrainScale":1}, camera: [7.718276497838673,46.017693318286575,12.873741518690931,78.00000000000001,-135], url: t3 },
  { spec: {"basemap":"ofm-bright","basemapVisible":true,"shading":"hillshade","shadingVisible":true,"exposure":null,"terrainScale":1}, camera: [7.718276497838673,46.017693318286575,12.873741518690931,78.00000000000001,-135], url: t4 },
  { spec: {"basemap":"ofm-dark","basemapVisible":true,"shading":"hillshade","shadingVisible":true,"exposure":null,"terrainScale":1}, camera: [7.718276497838673,46.017693318286575,12.873741518690931,78.00000000000001,-135], url: t5 },
  { spec: {"basemap":"ofm-positron","basemapVisible":true,"shading":"hillshade","shadingVisible":true,"exposure":null,"terrainScale":1}, camera: [7.718276497838673,46.017693318286575,12.873741518690931,78.00000000000001,-135], url: t6 },
  { spec: {"basemap":"satellite","basemapVisible":true,"shading":"hillshade","shadingVisible":true,"exposure":null,"terrainScale":1}, camera: [7.718276497838673,46.017693318286575,12.873741518690931,78.00000000000001,-135], url: t7 },
  { spec: {"basemap":"carto-dark","basemapVisible":true,"shading":"heatmap","shadingVisible":true,"exposure":null,"terrainScale":1}, camera: [7.718276497838673,46.017693318286575,12.873741518690931,78.00000000000001,-135], url: t8 },
  { spec: {"basemap":"carto-light","basemapVisible":true,"shading":"heatmap","shadingVisible":true,"exposure":null,"terrainScale":1}, camera: [7.718276497838673,46.017693318286575,12.873741518690931,78.00000000000001,-135], url: t9 },
  { spec: {"basemap":"carto-dark","basemapVisible":true,"shading":"heightmap","shadingVisible":true,"exposure":{"lo":223.2421875,"hi":4795.0859375},"terrainScale":1}, camera: [7.718276497838673,46.017693318286575,12.873741518690931,78.00000000000001,-135], url: t10 },
  { spec: {"basemap":"carto-light","basemapVisible":true,"shading":"heightmap","shadingVisible":true,"exposure":{"lo":223.2421875,"hi":4795.0859375},"terrainScale":1}, camera: [7.718276497838673,46.017693318286575,12.873741518690931,78.00000000000001,-135], url: t11 },
  { spec: {"basemap":"carto-light","basemapVisible":true,"shading":"hillshade","shadingVisible":true,"exposure":null,"terrainScale":1}, camera: [7.718276497838673,46.017693318286575,12.873741518690931,78.00000000000001,-135], url: t12 },
  { spec: {"basemap":"carto-dark","basemapVisible":true,"shading":"hillshade","shadingVisible":false,"exposure":null,"terrainScale":1}, camera: [7.718276497838673,46.017693318286575,12.873741518690931,78.00000000000001,-135], url: t13 },
  { spec: {"basemap":"carto-light","basemapVisible":true,"shading":"hillshade","shadingVisible":false,"exposure":null,"terrainScale":1}, camera: [7.718276497838673,46.017693318286575,12.873741518690931,78.00000000000001,-135], url: t14 },
];
